---
abstract: 'Tea round organising IRC bot'
author:
  - 'Adam Taylor <ajct@cpan.org>'
build_requires:
  English: 0
  Test::Bot::BasicBot::Pluggable: 0
  Test::MockModule: 0
  Test::MockObject::Extends: 0
  Test::More: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300008, CPAN::Meta::Converter version 2.120351'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bot-BasicBot-Pluggable-Module-Tea
requires:
  Bot::BasicBot::Pluggable::Module: 0
  DateTime: 0
  List::Util: 0
  Moose: 0
resources:
  repository: git://github.com/adamtaylor/bot-basicbot-pluggable-module-tea.git
version: 0.01
